### ISSUE TITLE
Swift 3 issue

### ISSUE THREAD

**Issue by proauto** [squimer/DatePickerDialog-iOS-Swift#47]
There's any plan to support swift3??

Thanks to your nice work, I use it very well but I have to upgrade swift version....

**Comment by lfarah** [comment]
Hey @proauto, we already support Swift 3 since last month. I just tested and installed the lib in one of my projects and everything works perfectly.

1. What error are you getting?
2. What version of the library do you have?
3. Are you using CocoaPods?

I'm going to close the issue and in case you're still having problems, I'll reopen!
